### ISSUE TITLE
Support CPU and Heap profiling online by demand

### ISSUE THREAD

**Issue by advancedxy** [zuston/legacy-riffle#10]
It's essential and useful to have a built-in profiling support such as [Databend](https://databend.rs/blog/profiling-rust)'s or BRpc's built-in support: https://github.com/apache/brpc/blob/master/docs/cn/heap_profiler.md and https://github.com/apache/brpc/blob/master/docs/cn/cpu_profiler.md

I would like to add this support before we are donating this to the Apache Uniffle(Incubating).

**Comment by zuston** [comment]
Great! I have tried this by jemalloc. 

Looking forward to putting this into master.

**Comment by advancedxy** [comment]
Didn't get time to work on the memory profiling part. Hopefully I can get it done this weekend.

**Comment by zuston** [comment]
Done.
